name: Assign VHP Identifier

on:
  issues:
    types: [opened]

jobs:
  assign-id:
    if: contains(github.event.issue.title, '[TERM REQUEST]')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Cache VHP IDs
        id: cache-ids
        uses: actions/cache@v3
        with:
          path: .vhp-cache
          key: vhp-ids-${{ hashFiles('templates/**/*.tsv') }}
          restore-keys: vhp-ids-
          
      - name: Extract and assign VHP ID
        id: assign-id
        run: python scripts/assign_vhp_id.py
          
      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            const vhpId = '${{ steps.assign-id.outputs.vhp_id }}';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🆔 **VHP Identifier Assigned:** \`${vhpId}\`\n\nThis identifier has been reserved for this term request.`
            });
