name: Assign VHP Identifier

on:
  issues:
    types: [opened]

jobs:
  assign-id:
    if: contains(github.event.issue.title, '[TERM REQUEST]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Fetch VHP cache from vhp-state branch
        run: |
          git fetch origin vhp-state
          git checkout origin/vhp-state -- .vhp-cache || echo "No cache found"

      - name: Extract and assign VHP ID
        id: assign-id
        run: python scripts/assign_vhp_id.py

      - name: Save updated VHP cache to branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git fetch origin vhp-state
          git checkout -b vhp-state origin/vhp-state || git checkout -b vhp-state
          git add .vhp-cache
          git commit -m "Update VHP cache after assignment [ci skip]" || echo "No changes to commit"
          git push origin vhp-state

      - name: Comment on issue
        uses: actions/github-script@v7
        with:
          script: |
            const vhpId = '${{ steps.assign-id.outputs.vhp_id }}';

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🆔 **VHP Identifier Assigned:** \`${vhpId}\`\n\nThis identifier has been reserved for this term request.`
            });
