name: Cleanup VHP Identifier

on:
  issues:
    types: [closed]

jobs:
  cleanup-id:
    if: contains(github.event.issue.title, '[TERM REQUEST]')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Cache VHP IDs
        id: cache-ids
        uses: actions/cache@v3
        with:
          path: .vhp-cache
          key: vhp-ids-${{ hashFiles('templates/**/*.tsv') }}
          restore-keys: vhp-ids-
          
      - name: Extract VHP ID from issue comments
        id: extract-id
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            let vhpId = null;
            for (const comment of comments.data) {
              const match = comment.body.match(/VHP Identifier Assigned.*`(VHP\d{7})`/);
              if (match) {
                vhpId = match[1];
                break;
              }
            }
            
            return vhpId;
          result-encoding: string
          
      - name: Cleanup unused VHP ID
        if: steps.extract-id.outputs.result != 'null'
        run: python scripts/cleanup_vhp_id.py '${{ steps.extract-id.outputs.result }}'
