name: update_md
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - templates/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install wheel setuptools pip --upgrade
        pip install pandas
    - name: Extract template data
      run: |
        python templateToMarkdown.py
    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
    - name: Commit and push changes
      if: env.CHANGES_DETECTED == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Updated glossary page" index.md
        git push origin ${{ github.head_ref }}
